default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: devops_interview_app_development
test:
  <<: *default
  database: devops_interview_app_test
production:
  <<: *default
  database: devops_interview_app_production
  username: devops_interview_app
  password: <%= ENV['DEVOPS_INTERVIEW_APP_DATABASE_PASSWORD'] %>
