# This workflow will build a docker container, publish it to Google Container Registry
#
# To configure this workflow:
#
# 1. Set up secrets in your workspace: GKE_PROJECT with the name of the project and GKE_SA_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 2. Change the values for the GKE_ZONE, APP_NAME, and ENVIRONMENT environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke

name: Build docker image and push to GCR

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-central2
  APP_NAME: devops-interview-app
  ENVIRONMENT: recruitment

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Cache Docker image
      - name: Pull image
        run: |-
          docker pull gcr.io/$PROJECT_ID/$APP_NAME:$ENVIRONMENT-latest || exit 0

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --progress=plain \
            --cache-from gcr.io/$PROJECT_ID/$APP_NAME:$ENVIRONMENT-latest \
            --tag "gcr.io/$PROJECT_ID/$APP_NAME:$ENVIRONMENT-$GITHUB_SHA" \
            --tag "gcr.io/$PROJECT_ID/$APP_NAME:$ENVIRONMENT-latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push --all-tags "gcr.io/$PROJECT_ID/$APP_NAME"
